/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { CustomerService } from "../customer.service";
import { CustomerCreateInput } from "./CustomerCreateInput";
import { Customer } from "./Customer";
import { CustomerFindManyArgs } from "./CustomerFindManyArgs";
import { CustomerWhereUniqueInput } from "./CustomerWhereUniqueInput";
import { CustomerUpdateInput } from "./CustomerUpdateInput";
import { AuthorizationFindManyArgs } from "../../authorization/base/AuthorizationFindManyArgs";
import { Authorization } from "../../authorization/base/Authorization";
import { AuthorizationWhereUniqueInput } from "../../authorization/base/AuthorizationWhereUniqueInput";
import { CreditCheckFindManyArgs } from "../../creditCheck/base/CreditCheckFindManyArgs";
import { CreditCheck } from "../../creditCheck/base/CreditCheck";
import { CreditCheckWhereUniqueInput } from "../../creditCheck/base/CreditCheckWhereUniqueInput";

export class CustomerControllerBase {
  constructor(protected readonly service: CustomerService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Customer })
  async createCustomer(
    @common.Body() data: CustomerCreateInput
  ): Promise<Customer> {
    return await this.service.createCustomer({
      data: data,
      select: {
        createdAt: true,
        dateOfBirth: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Customer] })
  @ApiNestedQuery(CustomerFindManyArgs)
  async customers(@common.Req() request: Request): Promise<Customer[]> {
    const args = plainToClass(CustomerFindManyArgs, request.query);
    return this.service.customers({
      ...args,
      select: {
        createdAt: true,
        dateOfBirth: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Customer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async customer(
    @common.Param() params: CustomerWhereUniqueInput
  ): Promise<Customer | null> {
    const result = await this.service.customer({
      where: params,
      select: {
        createdAt: true,
        dateOfBirth: true,
        email: true,
        firstName: true,
        id: true,
        lastName: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Customer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateCustomer(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() data: CustomerUpdateInput
  ): Promise<Customer | null> {
    try {
      return await this.service.updateCustomer({
        where: params,
        data: data,
        select: {
          createdAt: true,
          dateOfBirth: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Customer })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteCustomer(
    @common.Param() params: CustomerWhereUniqueInput
  ): Promise<Customer | null> {
    try {
      return await this.service.deleteCustomer({
        where: params,
        select: {
          createdAt: true,
          dateOfBirth: true,
          email: true,
          firstName: true,
          id: true,
          lastName: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/authorizations")
  @ApiNestedQuery(AuthorizationFindManyArgs)
  async findAuthorizations(
    @common.Req() request: Request,
    @common.Param() params: CustomerWhereUniqueInput
  ): Promise<Authorization[]> {
    const query = plainToClass(AuthorizationFindManyArgs, request.query);
    const results = await this.service.findAuthorizations(params.id, {
      ...query,
      select: {
        authCode: true,
        authDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/authorizations")
  async connectAuthorizations(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() body: AuthorizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      authorizations: {
        connect: body,
      },
    };
    await this.service.updateCustomer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/authorizations")
  async updateAuthorizations(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() body: AuthorizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      authorizations: {
        set: body,
      },
    };
    await this.service.updateCustomer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/authorizations")
  async disconnectAuthorizations(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() body: AuthorizationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      authorizations: {
        disconnect: body,
      },
    };
    await this.service.updateCustomer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/creditChecks")
  @ApiNestedQuery(CreditCheckFindManyArgs)
  async findCreditChecks(
    @common.Req() request: Request,
    @common.Param() params: CustomerWhereUniqueInput
  ): Promise<CreditCheck[]> {
    const query = plainToClass(CreditCheckFindManyArgs, request.query);
    const results = await this.service.findCreditChecks(params.id, {
      ...query,
      select: {
        checkDate: true,
        createdAt: true,
        creditLimit: true,
        creditScore: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/creditChecks")
  async connectCreditChecks(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() body: CreditCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      creditChecks: {
        connect: body,
      },
    };
    await this.service.updateCustomer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/creditChecks")
  async updateCreditChecks(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() body: CreditCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      creditChecks: {
        set: body,
      },
    };
    await this.service.updateCustomer({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/creditChecks")
  async disconnectCreditChecks(
    @common.Param() params: CustomerWhereUniqueInput,
    @common.Body() body: CreditCheckWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      creditChecks: {
        disconnect: body,
      },
    };
    await this.service.updateCustomer({
      where: params,
      data,
      select: { id: true },
    });
  }
}
