/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AuthorizationService } from "../authorization.service";
import { AuthorizationCreateInput } from "./AuthorizationCreateInput";
import { Authorization } from "./Authorization";
import { AuthorizationFindManyArgs } from "./AuthorizationFindManyArgs";
import { AuthorizationWhereUniqueInput } from "./AuthorizationWhereUniqueInput";
import { AuthorizationUpdateInput } from "./AuthorizationUpdateInput";
import { TransactionFindManyArgs } from "../../transaction/base/TransactionFindManyArgs";
import { Transaction } from "../../transaction/base/Transaction";
import { TransactionWhereUniqueInput } from "../../transaction/base/TransactionWhereUniqueInput";

export class AuthorizationControllerBase {
  constructor(protected readonly service: AuthorizationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Authorization })
  async createAuthorization(
    @common.Body() data: AuthorizationCreateInput
  ): Promise<Authorization> {
    return await this.service.createAuthorization({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        authCode: true,
        authDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Authorization] })
  @ApiNestedQuery(AuthorizationFindManyArgs)
  async authorizations(
    @common.Req() request: Request
  ): Promise<Authorization[]> {
    const args = plainToClass(AuthorizationFindManyArgs, request.query);
    return this.service.authorizations({
      ...args,
      select: {
        authCode: true,
        authDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Authorization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async authorization(
    @common.Param() params: AuthorizationWhereUniqueInput
  ): Promise<Authorization | null> {
    const result = await this.service.authorization({
      where: params,
      select: {
        authCode: true,
        authDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Authorization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAuthorization(
    @common.Param() params: AuthorizationWhereUniqueInput,
    @common.Body() data: AuthorizationUpdateInput
  ): Promise<Authorization | null> {
    try {
      return await this.service.updateAuthorization({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          authCode: true,
          authDate: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Authorization })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAuthorization(
    @common.Param() params: AuthorizationWhereUniqueInput
  ): Promise<Authorization | null> {
    try {
      return await this.service.deleteAuthorization({
        where: params,
        select: {
          authCode: true,
          authDate: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/transactions")
  @ApiNestedQuery(TransactionFindManyArgs)
  async findTransactions(
    @common.Req() request: Request,
    @common.Param() params: AuthorizationWhereUniqueInput
  ): Promise<Transaction[]> {
    const query = plainToClass(TransactionFindManyArgs, request.query);
    const results = await this.service.findTransactions(params.id, {
      ...query,
      select: {
        authCode: true,

        authorization: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        transactionAmount: true,
        transactionDate: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/transactions")
  async connectTransactions(
    @common.Param() params: AuthorizationWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        connect: body,
      },
    };
    await this.service.updateAuthorization({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/transactions")
  async updateTransactions(
    @common.Param() params: AuthorizationWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        set: body,
      },
    };
    await this.service.updateAuthorization({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/transactions")
  async disconnectTransactions(
    @common.Param() params: AuthorizationWhereUniqueInput,
    @common.Body() body: TransactionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      transactions: {
        disconnect: body,
      },
    };
    await this.service.updateAuthorization({
      where: params,
      data,
      select: { id: true },
    });
  }
}
